name: Task Tracker CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Frontend checks
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install Frontend Dependencies
        run: cd frontend && npm ci
      
      - name: Lint Frontend
        run: cd frontend && npm run lint
      
      - name: Test Frontend
        run: cd frontend && npm test -- --coverage
      
      # Backend checks
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install Backend Dependencies
        run: cd backend && npm ci
      
      - name: Lint Backend
        run: cd backend && npm run lint
      
      - name: Test Backend
        run: cd backend && npm test
  
  build-and-push:
    name: Build and Push Docker Images
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v4
        with:
          images: yourusername/tasktracker-frontend
          tags: |
            type=ref,event=branch
            type=sha,format=short
      
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=registry,ref=yourusername/tasktracker-frontend:buildcache
          cache-to: type=registry,ref=yourusername/tasktracker-frontend:buildcache,mode=max
      
      - name: Extract metadata for Backend
        id: meta-backend
        uses: docker/metadata-action@v4
        with:
          images: yourusername/tasktracker-backend
          tags: |
            type=ref,event=branch
            type=sha,format=short
      
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=registry,ref=yourusername/tasktracker-backend:buildcache
          cache-to: type=registry,ref=yourusername/tasktracker-backend:buildcache,mode=max
